package com.multivendor.ecommerce.entity;

import com.multivendor.ecommerce.entity.enums.SettlementStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * A payout batch: "here's everything we owe this vendor, generated on this
 * date, covering these sub-orders." Generated by an admin action that scoops
 * up every DELIVERED + paid VendorOrder for a vendor that isn't already part
 * of a settlement. Actually moving the money is a manual/external step —
 * see PaymentServiceImpl-style caveats in SettlementServiceImpl.
 */
@Entity
@Table(name = "settlements")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Settlement {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String settlementNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vendor_id", nullable = false)
    private Vendor vendor;

    @Builder.Default
    @OneToMany(mappedBy = "settlement", fetch = FetchType.EAGER)
    private List<VendorOrder> vendorOrders = new ArrayList<>();

    @Column(nullable = false)
    private Integer subOrderCount;

    @Column(nullable = false)
    private BigDecimal grossSales;

    @Column(nullable = false)
    private BigDecimal totalCommission;

    @Column(nullable = false)
    private BigDecimal netPayout;

    @Enumerated(EnumType.STRING)
    @Builder.Default
    @Column(nullable = false)
    private SettlementStatus status = SettlementStatus.PENDING;

    // Bank transfer reference / UTR number, filled in when marked PAID.
    private String paymentReference;

    private String notes;

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    private LocalDateTime paidAt;
}
